name: ci

on:

  release:

    types: [published]

    tag:

    - v1.*

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      -

        name: Checkout

        uses: actions/checkout@v2

      -

        name: Set up QEMU

        uses: docker/setup-qemu-action@v2

      -

        name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v2

      -

        name: Login to DockerHub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -

        name: Build and push

        uses: docker/build-push-action@v3

        with:

          context: .

          push: true

          tags: heinlinzaw/randnumimg:v1.0



      -

        name: Post message on slack

        uses: bluenovaio/action-slack@main

        with:

          username: "Hein Lin Zaw"

          icon_emoji: ":robot_face:"

          text:  "Name: Hein Lin Zaw \nMatriculation: A0249492R \nEmail: <outlook.com|E0941685@U.NUS.EDU> \nRepo: <https://github.com/HeinLinZaw96/randnum.git|git://https://github.com/HeinLinZaw96/randnum.git>\nImage name: heinlinzaw/randnumimg:${{github.ref_name}}\nImage url: <https://hub.docker.com/repository/docker/heinlinzaw/randnumimg|https://hub.docker.com/repository/docker/heinlinzaw/randnumimg>"

          webhook_url: ${{ secrets.SLACK_WEBHOOK }}